
version: "{branch} {build}"

build:
  verbosity: detailed

install:
  - cinst blender

build_script:
  - gradlew.bat spotlessApply --stacktrace --no-daemon
  - gradlew.bat assemble --stacktrace --no-daemon

test_script:
  - gradlew.bat check --stacktrace --no-daemon

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true
